### ISSUE TITLE
Response to blockchain failing to send when using Mongo

### ISSUE THREAD

**Issue by kss-espeo** [EspeoBlockchain/gardener-server#57]
Configure Gardener with `PERSISTENCE=MONGODB`
Send any query to Oracle
Query is processed by gardener-server
Expected: query response is sent to blockchain and no error messages are shown
Actual: sending query response fails with following error message:
```
Sending response failed [requestId=0xa2b8357552a4ae3ae94e99949a5ea45ff35f7e9e74657207cdcc2d5b2ec9c955] Error: No "from" address specified in neither the given options, nor the default options.
    at Object._executeMethod (/usr/src/app/node_modules/web3-eth-contract/src/index.js:832:45)
    at EthereumOracleAdapter._sendPendingResponse (/usr/src/app/src/infrastructure/blockchain/ethereum/EthereumOracleAdapter.js:73:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by kss-espeo** [comment]
Note that it does not seem to be reproducible on all machines. @kss-espeo can reproduce that, others (including our AWS environment) - can't.

**Comment by kss-espeo** [comment]
On hold until #60 is done, since I hope #60 will magically fix this.

**Comment by kss-espeo** [comment]
Couldn't reproduce this one.
